server:
  port: 9001
spring:
  application:
    name: tensquare-base  # 微服务名称，在单个微服务中名称是没用的！在服务调用时使用的
  datasource:
    url: jdbc:mysql://192.168.12.133:3306/tensquare_base?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true  # 打印sql语句
    generate-ddl: true # 自动建表（如果表存在，则不建表）
    database: mysql
eureka:
  client:
    register-with-eureka: true   # 把该服务注册到Eureka，被别的服务调用
    fetch-registry: true  # 该服务需要从Eureka获取其他服务的注册信息
    service-url:  # 向哪个Eureka注册
      defaultZone: http://127.0.0.1:6868/eureka
  instance:     # 如果服务在本地注册和调用，该配置可以省略；如果注册远程调用，该必须写的
    prefer-ip-address: true
