server: 
  port: 9010
spring: 
  application:  
    name: tensquare-friend #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.12.133:3306/tensquare_friend?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true  # 打印SQL语句
    generate-ddl: true # 自动建表(如果表存在，则不建表)
jwt:
  config:
    key: itcast
    ttl: 1800000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
